product-name: p-healthwatch
product-properties:
  .healthwatch-forwarder.boshhealth_instance_count:
    value: 1
  .healthwatch-forwarder.boshtasks_instance_count:
    value: 2
  .healthwatch-forwarder.canary_instance_count:
    value: 2
  .healthwatch-forwarder.cli_instance_count:
    value: 2
  .healthwatch-forwarder.health_check_az:
    value: pas-az1
  .healthwatch-forwarder.ingestor_instance_count:
    value: 4
  .healthwatch-forwarder.opsman_instance_count:
    value: 2
  .healthwatch-forwarder.publish_to_eva:
    value: true
  .healthwatch-forwarder.worker_instance_count:
    value: 4
  .mysql.skip_name_resolve:
    value: true
  .properties.boshtasks:
    selected_option: disable
    value: disable
  .properties.indicators_selector:
    selected_option: inactive
    value: "No"
  .properties.opsman:
    selected_option: disable
    value: disable
  .properties.syslog_selector:
    selected_option: inactive
    value: "No"
network-properties:
  network:
    name: PAS-Services
  other_availability_zones:
  - name: pas-az1
  - name: pas-az2
  - name: pas-az3
  service_network:
    name: PAS-Services
  singleton_availability_zone:
    name: pas-az1
resource-config:
  healthwatch-forwarder:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
  mysql:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
  redis:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
errand-config:
  delete-space:
    pre-delete-state: true
  push-apps:
    post-deploy-state: true
  smoke-tests:
    post-deploy-state: true
