product-name: pas-windows
product-properties:
  .properties.bosh_ssh_enabled:
    value: false
  .properties.enable_cf_metric_name:
    value: false
  .properties.kms:
    selected_option: disable
    value: disable
  .properties.rdp_enabled:
    value: false
  .properties.smoke_tests_windows:
    selected_option: on_demand
    value: on_demand
  .properties.system_logging:
    selected_option: disable
    value: disable
  .properties.windows_admin_password:
    selected_option: set_password
    value: set_password
  .properties.windows_admin_password.set_password.password:
    value:
      secret: pivotal123
network-properties:
  network:
    name: PAS-Deployment
  other_availability_zones:
  - name: pas-az1
  - name: pas-az2
  - name: pas-az3
  singleton_availability_zone:
    name: pas-az1
resource-config:
  windows_diego_cell:
    instances: automatic
    instance_type:
      id: automatic
errand-config:
  install-hwc-buildpack:
    post-deploy-state: true
  smoke_tests_windows:
    post-deploy-state: false